pipeline {
    agent any

    stages {
        stage("Test") {
            steps  {
                sh "pytest"
            }
        }

        stage("Build") {
            steps {
                sh "docker build -t jenkins-webapp:${GIT_COMMIT} ."
            }
        }
    }
}
